### PR TITLE
HAL CCM: add functions to trigger tasks and control interrupts

### PR DESCRIPTION
**Pull request by aescolar-ot**
Added CCM HAL functions to enable/disable its interrupts
and to trigger tasks

Signed-off-by: Alberto Escolar Piedras <alpi@oticon.com>

### CODE REVIEW

**Comment by kl-cruz** [comment]
HAL skeleton looks good, but there is code only to control few tasks and interrupts. 
Have you got plan to expand implementation to cover all tasks and other registers?

**Comment by aescolar-ot** [comment]
Thanks Karol. Those are the functions I needed so far. 
So, no plan from my side to add functions for the remaining registers.
Would it make sense to start with these, and, when needed expand it?

**Comment by kl-cruz** [comment]
I'd prefer to merge full solution for this peripheral. I could take over this task, cherry pick your commit and expand it.
What do you think about this kind of solution?

**Comment by aescolar-ot** [comment]
That's perfectly fine with me.

**Comment by anangl** [comment]
Replaced by #29.

**Pull request closed without merging**
